"""Generators: robots.txt for AI crawlers, llms.txt, and JSON-LD schema.

Pure stdlib. Outputs are deterministic given the same inputs.
See source/knowledge/02-crawler-logic.md and 04-webpage-architecture.md.
"""

import json


# --------------------------------------------------------------------------
# robots.txt
# --------------------------------------------------------------------------
_SEARCH_BOTS = ["Googlebot", "Bingbot", "Baiduspider"]
_AI_SEARCH_BOTS = ["OAI-SearchBot", "ChatGPT-User", "Claude-SearchBot",
                   "Claude-User", "PerplexityBot", "Perplexity-User"]
_AI_TRAIN_BOTS = ["GPTBot", "ClaudeBot", "Google-Extended", "CCBot",
                  "Applebot-Extended"]


def gen_robots(strategy="allow-all", sitemap=None, disallow_paths=None):
    """strategy:
      allow-all    -- maximize AI visibility, allow everything
      expose-only  -- allow AI search/citation, block training crawlers
      cn-index     -- China-first: ensure Baidu/Sogou/Bing index access
    """
    disallow_paths = disallow_paths or ["/admin/", "/api/"]
    lines = ["# Generated by HeiGe-GEO-SEO", "# strategy: %s" % strategy, ""]

    def block(ua_list, rule):
        for ua in ua_list:
            lines.append("User-agent: %s" % ua)
            lines.append(rule)
            lines.append("")

    if strategy == "allow-all":
        block(_SEARCH_BOTS + _AI_SEARCH_BOTS + _AI_TRAIN_BOTS, "Allow: /")
    elif strategy == "expose-only":
        lines.append("# 搜索引擎与 AI 检索/引用类:放行")
        lines.append("")
        block(_SEARCH_BOTS + _AI_SEARCH_BOTS, "Allow: /")
        lines.append("# AI 训练类:拒绝(只要曝光不喂训练)")
        lines.append("")
        block(_AI_TRAIN_BOTS, "Disallow: /")
    elif strategy == "cn-index":
        lines.append("# 国内 GEO:确保百度/搜狗/必应能收录(国产 AI 的总进水口)")
        lines.append("")
        block(["Baiduspider", "Sogou web spider", "Bingbot", "Googlebot"], "Allow: /")
        lines.append("# AI 检索类一并放行")
        lines.append("")
        block(_AI_SEARCH_BOTS, "Allow: /")
        lines.append("# 字节 Bytespider 抓取激进,如需限制在防火墙层加 IP/UA 拦截")
        lines.append("")
    else:
        raise ValueError("unknown strategy: %s" % strategy)

    lines.append("# 兜底")
    lines.append("User-agent: *")
    lines.append("Allow: /")
    for p in disallow_paths:
        lines.append("Disallow: %s" % p)
    lines.append("")
    if sitemap:
        lines.append("Sitemap: %s" % sitemap)
    return "\n".join(lines).rstrip() + "\n"


# --------------------------------------------------------------------------
# llms.txt
# --------------------------------------------------------------------------
def gen_llms_txt(site_name, summary, sections=None, body=None):
    """sections: list of {'title': str, 'links': [{'name','url','desc'}]}"""
    out = ["# %s" % site_name, ""]
    if summary:
        out.append("> %s" % summary)
        out.append("")
    if body:
        out.append(body.strip())
        out.append("")
    for sec in (sections or []):
        out.append("## %s" % sec["title"])
        for link in sec.get("links", []):
            desc = link.get("desc")
            line = "- [%s](%s)" % (link["name"], link["url"])
            if desc:
                line += ": %s" % desc
            out.append(line)
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def parse_links_file(text):
    """Parse a simple links file into one section.
    Each line: url | name | description   (description optional)."""
    links = []
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        parts = [p.strip() for p in line.split("|")]
        url = parts[0]
        name = parts[1] if len(parts) > 1 and parts[1] else url
        desc = parts[2] if len(parts) > 2 else None
        links.append({"name": name, "url": url, "desc": desc})
    return links


# --------------------------------------------------------------------------
# JSON-LD schema
# --------------------------------------------------------------------------
def gen_article(title, description="", author=None, org=None, url=None,
                date_published=None, date_modified=None, image=None,
                author_url=None, same_as=None):
    node = {
        "@context": "https://schema.org",
        "@type": "Article",
        "headline": title,
    }
    if description:
        node["description"] = description
    if image:
        node["image"] = image
    if date_published:
        node["datePublished"] = date_published
    if date_modified or date_published:
        node["dateModified"] = date_modified or date_published
    if url:
        node["mainEntityOfPage"] = {"@type": "WebPage", "@id": url}
    if author:
        a = {"@type": "Person", "name": author}
        if author_url:
            a["@id"] = author_url
        if same_as:
            a["sameAs"] = same_as
        node["author"] = a
    if org:
        node["publisher"] = {"@type": "Organization", "name": org}
    return node


def gen_faqpage(qa_pairs):
    """qa_pairs: list of (question, answer)."""
    return {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        "mainEntity": [
            {"@type": "Question", "name": q,
             "acceptedAnswer": {"@type": "Answer", "text": a}}
            for q, a in qa_pairs
        ],
    }


def gen_howto(name, steps):
    """steps: list of (step_name, step_text)."""
    return {
        "@context": "https://schema.org",
        "@type": "HowTo",
        "name": name,
        "step": [
            {"@type": "HowToStep", "position": i + 1, "name": sn, "text": st}
            for i, (sn, st) in enumerate(steps)
        ],
    }


def gen_product(name, description="", brand=None, price=None, currency="CNY",
                rating=None, rating_count=None):
    node = {
        "@context": "https://schema.org",
        "@type": "Product",
        "name": name,
    }
    if description:
        node["description"] = description
    if brand:
        node["brand"] = {"@type": "Brand", "name": brand}
    if price is not None:
        node["offers"] = {"@type": "Offer", "price": str(price),
                          "priceCurrency": currency}
    if rating is not None:
        agg = {"@type": "AggregateRating", "ratingValue": str(rating)}
        if rating_count is not None:
            agg["ratingCount"] = str(rating_count)
        node["aggregateRating"] = agg
    return node


def to_script(node):
    body = json.dumps(node, ensure_ascii=False, indent=2)
    return '<script type="application/ld+json">\n%s\n</script>' % body
