"""Generators: robots.txt for AI crawlers, llms.txt, and JSON-LD schema.

Pure stdlib. Outputs are deterministic given the same inputs.
See source/knowledge/02-crawler-logic.md and 04-webpage-architecture.md.
"""

import json


# --------------------------------------------------------------------------
# robots.txt
# --------------------------------------------------------------------------
_SEARCH_BOTS = ["Googlebot", "Bingbot", "Baiduspider"]
_AI_SEARCH_BOTS = ["OAI-SearchBot", "ChatGPT-User", "Claude-SearchBot",
                   "Claude-User", "PerplexityBot", "Perplexity-User"]
_AI_TRAIN_BOTS = ["GPTBot", "ClaudeBot", "Google-Extended", "CCBot",
                  "Applebot-Extended"]


def gen_robots(strategy="allow-all", sitemap=None, disallow_paths=None):
    """strategy:
      allow-all    -- maximize AI visibility, allow everything
      expose-only  -- allow AI search/citation, block training crawlers
      cn-index     -- China-first: ensure Baidu/Sogou/Bing index access
    """
    disallow_paths = disallow_paths or ["/admin/", "/api/"]
    lines = ["# Generated by HeiGe-GEO-SEO", "# strategy: %s" % strategy, ""]

    def block(ua_list, rule):
        for ua in ua_list:
            lines.append("User-agent: %s" % ua)
            lines.append(rule)
            lines.append("")

    if strategy == "allow-all":
        block(_SEARCH_BOTS + _AI_SEARCH_BOTS + _AI_TRAIN_BOTS, "Allow: /")
    elif strategy == "expose-only":
        lines.append("# 搜索引擎与 AI 检索/引用类:放行")
        lines.append("")
        block(_SEARCH_BOTS + _AI_SEARCH_BOTS, "Allow: /")
        lines.append("# AI 训练类:拒绝(只要曝光不喂训练)")
        lines.append("")
        block(_AI_TRAIN_BOTS, "Disallow: /")
    elif strategy == "cn-index":
        lines.append("# 国内 GEO:确保百度/搜狗/必应能收录(国产 AI 的总进水口)")
        lines.append("")
        block(["Baiduspider", "Sogou web spider", "Bingbot", "Googlebot"], "Allow: /")
        lines.append("# AI 检索类一并放行")
        lines.append("")
        block(_AI_SEARCH_BOTS, "Allow: /")
        lines.append("# 字节 Bytespider 抓取激进,如需限制在防火墙层加 IP/UA 拦截")
        lines.append("")
    else:
        raise ValueError("unknown strategy: %s" % strategy)

    lines.append("# 兜底")
    lines.append("User-agent: *")
    lines.append("Allow: /")
    for p in disallow_paths:
        lines.append("Disallow: %s" % p)
    lines.append("")
    if sitemap:
        lines.append("Sitemap: %s" % sitemap)
    return "\n".join(lines).rstrip() + "\n"


# --------------------------------------------------------------------------
# llms.txt
# --------------------------------------------------------------------------
def gen_llms_txt(site_name, summary, sections=None, body=None):
    """sections: list of {'title': str, 'links': [{'name','url','desc'}]}"""
    out = ["# %s" % site_name, ""]
    if summary:
        out.append("> %s" % summary)
        out.append("")
    if body:
        out.append(body.strip())
        out.append("")
    for sec in (sections or []):
        out.append("## %s" % sec["title"])
        for link in sec.get("links", []):
            desc = link.get("desc")
            line = "- [%s](%s)" % (link["name"], link["url"])
            if desc:
                line += ": %s" % desc
            out.append(line)
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def parse_links_file(text):
    """Parse a simple links file into one section.
    Each line: url | name | description   (description optional)."""
    links = []
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        parts = [p.strip() for p in line.split("|")]
        url = parts[0]
        name = parts[1] if len(parts) > 1 and parts[1] else url
        desc = parts[2] if len(parts) > 2 else None
        links.append({"name": name, "url": url, "desc": desc})
    return links


# --------------------------------------------------------------------------
# JSON-LD schema
# --------------------------------------------------------------------------
def gen_article(title, description="", author=None, org=None, url=None,
                date_published=None, date_modified=None, image=None,
                author_url=None, same_as=None):
    node = {
        "@context": "https://schema.org",
        "@type": "Article",
        "headline": title,
    }
    if description:
        node["description"] = description
    if image:
        node["image"] = image
    if date_published:
        node["datePublished"] = date_published
    if date_modified or date_published:
        node["dateModified"] = date_modified or date_published
    if url:
        node["mainEntityOfPage"] = {"@type": "WebPage", "@id": url}
    if author:
        a = {"@type": "Person", "name": author}
        if author_url:
            a["@id"] = author_url
        if same_as:
            a["sameAs"] = same_as
        node["author"] = a
    if org:
        node["publisher"] = {"@type": "Organization", "name": org}
    return node


def gen_faqpage(qa_pairs):
    """qa_pairs: list of (question, answer)."""
    return {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        "mainEntity": [
            {"@type": "Question", "name": q,
             "acceptedAnswer": {"@type": "Answer", "text": a}}
            for q, a in qa_pairs
        ],
    }


def gen_howto(name, steps):
    """steps: list of (step_name, step_text)."""
    return {
        "@context": "https://schema.org",
        "@type": "HowTo",
        "name": name,
        "step": [
            {"@type": "HowToStep", "position": i + 1, "name": sn, "text": st}
            for i, (sn, st) in enumerate(steps)
        ],
    }


def gen_product(name, description="", brand=None, price=None, currency="CNY",
                rating=None, rating_count=None):
    node = {
        "@context": "https://schema.org",
        "@type": "Product",
        "name": name,
    }
    if description:
        node["description"] = description
    if brand:
        node["brand"] = {"@type": "Brand", "name": brand}
    if price is not None:
        node["offers"] = {"@type": "Offer", "price": str(price),
                          "priceCurrency": currency}
    if rating is not None:
        agg = {"@type": "AggregateRating", "ratingValue": str(rating)}
        if rating_count is not None:
            agg["ratingCount"] = str(rating_count)
        node["aggregateRating"] = agg
    return node


def gen_organization(name, url=None, logo=None, same_as=None, founder=None,
                     description=""):
    """Entity-layer schema. @id + sameAs are the AI-citation gatekeepers."""
    node = {
        "@context": "https://schema.org",
        "@type": "Organization",
        "name": name,
    }
    if url:
        node["@id"] = url.rstrip("/") + "/#org"
        node["url"] = url
    if description:
        node["description"] = description
    if logo:
        node["logo"] = {"@type": "ImageObject", "url": logo}
    if same_as:
        node["sameAs"] = same_as
    if founder:
        node["founder"] = {"@type": "Person", "name": founder}
    return node


def gen_person(name, job_title=None, url=None, knows_about=None, same_as=None,
               works_for=None):
    node = {
        "@context": "https://schema.org",
        "@type": "Person",
        "name": name,
    }
    if url:
        node["@id"] = url
    if job_title:
        node["jobTitle"] = job_title
    if knows_about:
        node["knowsAbout"] = knows_about
    if same_as:
        node["sameAs"] = same_as
    if works_for:
        node["worksFor"] = {"@type": "Organization", "name": works_for}
    return node


def gen_website(name, url, publisher=None):
    node = {
        "@context": "https://schema.org",
        "@type": "WebSite",
        "name": name,
        "url": url,
    }
    if url:
        node["@id"] = url.rstrip("/") + "/#website"
    if publisher:
        node["publisher"] = {"@type": "Organization", "name": publisher}
    return node


def gen_breadcrumb(items):
    """BreadcrumbList。知识库 04 标为全站每页建议上。
    items: list of (name, url) 或 (name,)(最后一项可无 url)。"""
    elements = []
    for i, item in enumerate(items, 1):
        name = item[0] if isinstance(item, (list, tuple)) else item
        el = {"@type": "ListItem", "position": i, "name": name}
        if isinstance(item, (list, tuple)) and len(item) > 1 and item[1]:
            el["item"] = item[1]
        elements.append(el)
    return {"@context": "https://schema.org", "@type": "BreadcrumbList",
            "itemListElement": elements}


def gen_itemlist(name, items):
    """ItemList。知识库 04/08 标为'最好的 X'/榜单对比页命中尤其有效。
    items: list of (name, url) 或 dict(可嵌 Product)。"""
    elements = []
    for i, item in enumerate(items, 1):
        if isinstance(item, dict):
            el = {"@type": "ListItem", "position": i, "item": item}
        else:
            nm = item[0] if isinstance(item, (list, tuple)) else item
            el = {"@type": "ListItem", "position": i, "name": nm}
            if isinstance(item, (list, tuple)) and len(item) > 1 and item[1]:
                el["url"] = item[1]
        elements.append(el)
    return {"@context": "https://schema.org", "@type": "ItemList",
            "name": name, "itemListElement": elements}


def gen_review(item_name, rating, author, body="", best_rating="5"):
    """Review。知识库 04 产品/工具页建议上。"""
    node = {
        "@context": "https://schema.org",
        "@type": "Review",
        "itemReviewed": {"@type": "Thing", "name": item_name},
        "reviewRating": {"@type": "Rating", "ratingValue": str(rating),
                         "bestRating": str(best_rating)},
        "author": {"@type": "Person", "name": author},
    }
    if body:
        node["reviewBody"] = body
    return node


def gen_graph(*nodes):
    """把多个 schema 节点用 @graph 串成一个图(知识库 04 第2节核心原则:用 @id 关联,
    别各自孤立)。每个节点去掉自带 @context,顶层统一一个。"""
    graph = []
    for n in nodes:
        if not n:
            continue
        m = dict(n)
        m.pop("@context", None)
        graph.append(m)
    return {"@context": "https://schema.org", "@graph": graph}


def to_script(node):
    body = json.dumps(node, ensure_ascii=False, indent=2)
    return '<script type="application/ld+json">\n%s\n</script>' % body


# --------------------------------------------------------------------------
# AI discovery / answer files (the aeorank 9-file family, deterministic)
# --------------------------------------------------------------------------
_AI_BOTS_3LAYER = [
    ("GPTBot", "train"), ("OAI-SearchBot", "search"), ("ChatGPT-User", "user"),
    ("ClaudeBot", "train"), ("Claude-SearchBot", "search"), ("Claude-User", "user"),
    ("PerplexityBot", "search"), ("Google-Extended", "train"),
]


def gen_ai_txt(allow_train=False, citation_required=True):
    """ai.txt — content usage policy, separate from robots.txt."""
    lines = ["# ai.txt — content usage policy",
             "# Generated by HeiGe-GEO-SEO", ""]
    for bot, kind in _AI_BOTS_3LAYER:
        if kind == "train" and not allow_train:
            lines.append("User-Agent: %s" % bot)
            lines.append("Disallow: /")
            lines.append("Content-Usage: train=no")
        else:
            lines.append("User-Agent: %s" % bot)
            lines.append("Allow: /")
            if kind == "search" and citation_required:
                lines.append("Citation: required")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def gen_robots_patch(allow_train=True):
    """robots.patch — surgical diff that only adds AI-bot allow lines."""
    adds = ["GPTBot", "OAI-SearchBot", "ClaudeBot", "Claude-SearchBot",
            "PerplexityBot", "Google-Extended"] if allow_train else \
           ["OAI-SearchBot", "Claude-SearchBot", "PerplexityBot"]
    lines = ["--- a/robots.txt", "+++ b/robots.txt", "@@ AI crawlers @@"]
    for ua in adds:
        lines.append("+User-agent: %s" % ua)
        lines.append("+Allow: /")
    return "\n".join(lines) + "\n"


def gen_sitemap(urls):
    """urls: list of (loc, lastmod) or just loc strings."""
    out = ['<?xml version="1.0" encoding="UTF-8"?>',
           '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
    for u in urls:
        if isinstance(u, (list, tuple)):
            loc, lastmod = u[0], (u[1] if len(u) > 1 else None)
        else:
            loc, lastmod = u, None
        if lastmod:
            out.append("  <url><loc>%s</loc><lastmod>%s</lastmod></url>" % (loc, lastmod))
        else:
            out.append("  <url><loc>%s</loc></url>" % loc)
    out.append("</urlset>")
    return "\n".join(out) + "\n"


def gen_answers_json(qa_items):
    """answers.json — top Q&A in machine-citable format.
    qa_items: list of (q, a, url) or (q, a)."""
    answers = []
    for item in qa_items:
        q, a = item[0], item[1]
        rec = {"q": q, "a": a}
        if len(item) > 2 and item[2]:
            rec["url"] = item[2]
        answers.append(rec)
    return json.dumps({"version": "1.0", "answers": answers},
                      ensure_ascii=False, indent=2) + "\n"


def gen_citations_json(citations):
    """citations.json — first-party sources backing site claims.
    citations: list of dict(claim, source, date[, id])."""
    out = []
    for i, c in enumerate(citations, 1):
        rec = {"id": c.get("id", i), "claim": c["claim"], "source": c["source"]}
        if c.get("date"):
            rec["date"] = c["date"]
        out.append(rec)
    return json.dumps({"citations": out}, ensure_ascii=False, indent=2) + "\n"


def gen_humans_txt(team=None, site=None, standards=None, last_update=None):
    """humans.txt — author / team metadata feeding E-E-A-T author signal."""
    lines = ["/* TEAM */"]
    for role, name in (team or []):
        lines.append("%s: %s" % (role, name))
    lines.append("")
    lines.append("/* SITE */")
    if site:
        lines.append("Site: %s" % site)
    if standards:
        lines.append("Standards: %s" % ", ".join(standards))
    if last_update:
        lines.append("Last update: %s" % last_update)
    return "\n".join(lines) + "\n"


def gen_feed_xml(title, link, items, last_build=None):
    """feed.xml — RSS freshness signal. items: list of (title, pubdate[, link])."""
    out = ['<?xml version="1.0" encoding="UTF-8"?>',
           '<rss version="2.0"><channel>',
           "  <title>%s</title>" % title,
           "  <link>%s</link>" % link]
    if last_build:
        out.append("  <lastBuildDate>%s</lastBuildDate>" % last_build)
    for item in items:
        t, pub = item[0], item[1]
        il = item[2] if len(item) > 2 else link
        out.append("  <item><title>%s</title><link>%s</link><pubDate>%s</pubDate></item>"
                   % (t, il, pub))
    out.append("</channel></rss>")
    return "\n".join(out) + "\n"
